/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BoysRouteImport } from './routes/boys'
import { Route as CommunionRouteImport } from './routes/communion'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as GirlsRouteImport } from './routes/girls'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SalesPointsRouteImport } from './routes/sales-points'
import { Route as SilkRouteImport } from './routes/silk'
import { Route as AccessoriesIndexRouteImport } from './routes/accessories.index'
import { Route as AccessoriesCodeRouteImport } from './routes/accessories.$code'
import { Route as BoysIndexRouteImport } from './routes/boys.index'
import { Route as BoysCodeRouteImport } from './routes/boys.$code'
import { Route as CommunionIndexRouteImport } from './routes/communion.index'
import { Route as CommunionCodeRouteImport } from './routes/communion.$code'
import { Route as GirlsIndexRouteImport } from './routes/girls.index'
import { Route as GirlsCodeRouteImport } from './routes/girls.$code'
import { Route as SilkIndexRouteImport } from './routes/silk.index'
import { Route as SilkCodeRouteImport } from './routes/silk.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BoysRoute = BoysRouteImport.update({
  id: '/boys',
  path: '/boys',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunionRoute = CommunionRouteImport.update({
  id: '/communion',
  path: '/communion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const GirlsRoute = GirlsRouteImport.update({
  id: '/girls',
  path: '/girls',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesPointsRoute = SalesPointsRouteImport.update({
  id: '/sales-points',
  path: '/sales-points',
  getParentRoute: () => rootRouteImport,
} as any)
const SilkRoute = SilkRouteImport.update({
  id: '/silk',
  path: '/silk',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesIndexRoute = AccessoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccessoriesRoute,
} as any)
const AccessoriesCodeRoute = AccessoriesCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => AccessoriesRoute,
} as any)
const BoysIndexRoute = BoysIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoysRoute,
} as any)
const BoysCodeRoute = BoysCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => BoysRoute,
} as any)
const CommunionIndexRoute = CommunionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunionRoute,
} as any)
const CommunionCodeRoute = CommunionCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => CommunionRoute,
} as any)
const GirlsIndexRoute = GirlsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GirlsRoute,
} as any)
const GirlsCodeRoute = GirlsCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => GirlsRoute,
} as any)
const SilkIndexRoute = SilkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SilkRoute,
} as any)
const SilkCodeRoute = SilkCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => SilkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/boys': typeof BoysRouteWithChildren
  '/communion': typeof CommunionRouteWithChildren
  '/contact': typeof ContactRoute
  '/gdpr': typeof GdprRoute
  '/girls': typeof GirlsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sales-points': typeof SalesPointsRoute
  '/silk': typeof SilkRouteWithChildren
  '/accessories/$code': typeof AccessoriesCodeRoute
  '/boys/$code': typeof BoysCodeRoute
  '/communion/$code': typeof CommunionCodeRoute
  '/girls/$code': typeof GirlsCodeRoute
  '/silk/$code': typeof SilkCodeRoute
  '/accessories/': typeof AccessoriesIndexRoute
  '/boys/': typeof BoysIndexRoute
  '/communion/': typeof CommunionIndexRoute
  '/girls/': typeof GirlsIndexRoute
  '/silk/': typeof SilkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/gdpr': typeof GdprRoute
  '/privacy': typeof PrivacyRoute
  '/sales-points': typeof SalesPointsRoute
  '/accessories/$code': typeof AccessoriesCodeRoute
  '/boys/$code': typeof BoysCodeRoute
  '/communion/$code': typeof CommunionCodeRoute
  '/girls/$code': typeof GirlsCodeRoute
  '/silk/$code': typeof SilkCodeRoute
  '/accessories': typeof AccessoriesIndexRoute
  '/boys': typeof BoysIndexRoute
  '/communion': typeof CommunionIndexRoute
  '/girls': typeof GirlsIndexRoute
  '/silk': typeof SilkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/boys': typeof BoysRouteWithChildren
  '/communion': typeof CommunionRouteWithChildren
  '/contact': typeof ContactRoute
  '/gdpr': typeof GdprRoute
  '/girls': typeof GirlsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sales-points': typeof SalesPointsRoute
  '/silk': typeof SilkRouteWithChildren
  '/accessories/$code': typeof AccessoriesCodeRoute
  '/boys/$code': typeof BoysCodeRoute
  '/communion/$code': typeof CommunionCodeRoute
  '/girls/$code': typeof GirlsCodeRoute
  '/silk/$code': typeof SilkCodeRoute
  '/accessories/': typeof AccessoriesIndexRoute
  '/boys/': typeof BoysIndexRoute
  '/communion/': typeof CommunionIndexRoute
  '/girls/': typeof GirlsIndexRoute
  '/silk/': typeof SilkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessories'
    | '/admin'
    | '/auth'
    | '/boys'
    | '/communion'
    | '/contact'
    | '/gdpr'
    | '/girls'
    | '/privacy'
    | '/sales-points'
    | '/silk'
    | '/accessories/$code'
    | '/boys/$code'
    | '/communion/$code'
    | '/girls/$code'
    | '/silk/$code'
    | '/accessories/'
    | '/boys/'
    | '/communion/'
    | '/girls/'
    | '/silk/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/gdpr'
    | '/privacy'
    | '/sales-points'
    | '/accessories/$code'
    | '/boys/$code'
    | '/communion/$code'
    | '/girls/$code'
    | '/silk/$code'
    | '/accessories'
    | '/boys'
    | '/communion'
    | '/girls'
    | '/silk'
  id:
    | '__root__'
    | '/'
    | '/accessories'
    | '/admin'
    | '/auth'
    | '/boys'
    | '/communion'
    | '/contact'
    | '/gdpr'
    | '/girls'
    | '/privacy'
    | '/sales-points'
    | '/silk'
    | '/accessories/$code'
    | '/boys/$code'
    | '/communion/$code'
    | '/girls/$code'
    | '/silk/$code'
    | '/accessories/'
    | '/boys/'
    | '/communion/'
    | '/girls/'
    | '/silk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessoriesRoute: typeof AccessoriesRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BoysRoute: typeof BoysRouteWithChildren
  CommunionRoute: typeof CommunionRouteWithChildren
  ContactRoute: typeof ContactRoute
  GdprRoute: typeof GdprRoute
  GirlsRoute: typeof GirlsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SalesPointsRoute: typeof SalesPointsRoute
  SilkRoute: typeof SilkRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boys': {
      id: '/boys'
      path: '/boys'
      fullPath: '/boys'
      preLoaderRoute: typeof BoysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communion': {
      id: '/communion'
      path: '/communion'
      fullPath: '/communion'
      preLoaderRoute: typeof CommunionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/girls': {
      id: '/girls'
      path: '/girls'
      fullPath: '/girls'
      preLoaderRoute: typeof GirlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-points': {
      id: '/sales-points'
      path: '/sales-points'
      fullPath: '/sales-points'
      preLoaderRoute: typeof SalesPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/silk': {
      id: '/silk'
      path: '/silk'
      fullPath: '/silk'
      preLoaderRoute: typeof SilkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories/': {
      id: '/accessories/'
      path: '/'
      fullPath: '/accessories/'
      preLoaderRoute: typeof AccessoriesIndexRouteImport
      parentRoute: typeof AccessoriesRoute
    }
    '/accessories/$code': {
      id: '/accessories/$code'
      path: '/$code'
      fullPath: '/accessories/$code'
      preLoaderRoute: typeof AccessoriesCodeRouteImport
      parentRoute: typeof AccessoriesRoute
    }
    '/boys/': {
      id: '/boys/'
      path: '/'
      fullPath: '/boys/'
      preLoaderRoute: typeof BoysIndexRouteImport
      parentRoute: typeof BoysRoute
    }
    '/boys/$code': {
      id: '/boys/$code'
      path: '/$code'
      fullPath: '/boys/$code'
      preLoaderRoute: typeof BoysCodeRouteImport
      parentRoute: typeof BoysRoute
    }
    '/communion/': {
      id: '/communion/'
      path: '/'
      fullPath: '/communion/'
      preLoaderRoute: typeof CommunionIndexRouteImport
      parentRoute: typeof CommunionRoute
    }
    '/communion/$code': {
      id: '/communion/$code'
      path: '/$code'
      fullPath: '/communion/$code'
      preLoaderRoute: typeof CommunionCodeRouteImport
      parentRoute: typeof CommunionRoute
    }
    '/girls/': {
      id: '/girls/'
      path: '/'
      fullPath: '/girls/'
      preLoaderRoute: typeof GirlsIndexRouteImport
      parentRoute: typeof GirlsRoute
    }
    '/girls/$code': {
      id: '/girls/$code'
      path: '/$code'
      fullPath: '/girls/$code'
      preLoaderRoute: typeof GirlsCodeRouteImport
      parentRoute: typeof GirlsRoute
    }
    '/silk/': {
      id: '/silk/'
      path: '/'
      fullPath: '/silk/'
      preLoaderRoute: typeof SilkIndexRouteImport
      parentRoute: typeof SilkRoute
    }
    '/silk/$code': {
      id: '/silk/$code'
      path: '/$code'
      fullPath: '/silk/$code'
      preLoaderRoute: typeof SilkCodeRouteImport
      parentRoute: typeof SilkRoute
    }
  }
}

interface AccessoriesRouteChildren {
  AccessoriesCodeRoute: typeof AccessoriesCodeRoute
  AccessoriesIndexRoute: typeof AccessoriesIndexRoute
}

const AccessoriesRouteChildren: AccessoriesRouteChildren = {
  AccessoriesCodeRoute: AccessoriesCodeRoute,
  AccessoriesIndexRoute: AccessoriesIndexRoute,
}

const AccessoriesRouteWithChildren = AccessoriesRoute._addFileChildren(
  AccessoriesRouteChildren,
)

interface BoysRouteChildren {
  BoysCodeRoute: typeof BoysCodeRoute
  BoysIndexRoute: typeof BoysIndexRoute
}

const BoysRouteChildren: BoysRouteChildren = {
  BoysCodeRoute: BoysCodeRoute,
  BoysIndexRoute: BoysIndexRoute,
}

const BoysRouteWithChildren = BoysRoute._addFileChildren(BoysRouteChildren)

interface CommunionRouteChildren {
  CommunionCodeRoute: typeof CommunionCodeRoute
  CommunionIndexRoute: typeof CommunionIndexRoute
}

const CommunionRouteChildren: CommunionRouteChildren = {
  CommunionCodeRoute: CommunionCodeRoute,
  CommunionIndexRoute: CommunionIndexRoute,
}

const CommunionRouteWithChildren = CommunionRoute._addFileChildren(
  CommunionRouteChildren,
)

interface GirlsRouteChildren {
  GirlsCodeRoute: typeof GirlsCodeRoute
  GirlsIndexRoute: typeof GirlsIndexRoute
}

const GirlsRouteChildren: GirlsRouteChildren = {
  GirlsCodeRoute: GirlsCodeRoute,
  GirlsIndexRoute: GirlsIndexRoute,
}

const GirlsRouteWithChildren = GirlsRoute._addFileChildren(GirlsRouteChildren)

interface SilkRouteChildren {
  SilkCodeRoute: typeof SilkCodeRoute
  SilkIndexRoute: typeof SilkIndexRoute
}

const SilkRouteChildren: SilkRouteChildren = {
  SilkCodeRoute: SilkCodeRoute,
  SilkIndexRoute: SilkIndexRoute,
}

const SilkRouteWithChildren = SilkRoute._addFileChildren(SilkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessoriesRoute: AccessoriesRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BoysRoute: BoysRouteWithChildren,
  CommunionRoute: CommunionRouteWithChildren,
  ContactRoute: ContactRoute,
  GdprRoute: GdprRoute,
  GirlsRoute: GirlsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SalesPointsRoute: SalesPointsRoute,
  SilkRoute: SilkRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
