/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SilkRouteImport } from './routes/silk'
import { Route as SalesPointsRouteImport } from './routes/sales-points'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GirlsRouteImport } from './routes/girls'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunionRouteImport } from './routes/communion'
import { Route as BoysRouteImport } from './routes/boys'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoysCodeRouteImport } from './routes/boys.$code'

const SilkRoute = SilkRouteImport.update({
  id: '/silk',
  path: '/silk',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesPointsRoute = SalesPointsRouteImport.update({
  id: '/sales-points',
  path: '/sales-points',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GirlsRoute = GirlsRouteImport.update({
  id: '/girls',
  path: '/girls',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunionRoute = CommunionRouteImport.update({
  id: '/communion',
  path: '/communion',
  getParentRoute: () => rootRouteImport,
} as any)
const BoysRoute = BoysRouteImport.update({
  id: '/boys',
  path: '/boys',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoysCodeRoute = BoysCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => BoysRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/boys': typeof BoysRouteWithChildren
  '/communion': typeof CommunionRoute
  '/contact': typeof ContactRoute
  '/gdpr': typeof GdprRoute
  '/girls': typeof GirlsRoute
  '/privacy': typeof PrivacyRoute
  '/sales-points': typeof SalesPointsRoute
  '/silk': typeof SilkRoute
  '/boys/$code': typeof BoysCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/boys': typeof BoysRouteWithChildren
  '/communion': typeof CommunionRoute
  '/contact': typeof ContactRoute
  '/gdpr': typeof GdprRoute
  '/girls': typeof GirlsRoute
  '/privacy': typeof PrivacyRoute
  '/sales-points': typeof SalesPointsRoute
  '/silk': typeof SilkRoute
  '/boys/$code': typeof BoysCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/boys': typeof BoysRouteWithChildren
  '/communion': typeof CommunionRoute
  '/contact': typeof ContactRoute
  '/gdpr': typeof GdprRoute
  '/girls': typeof GirlsRoute
  '/privacy': typeof PrivacyRoute
  '/sales-points': typeof SalesPointsRoute
  '/silk': typeof SilkRoute
  '/boys/$code': typeof BoysCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessories'
    | '/admin'
    | '/auth'
    | '/boys'
    | '/communion'
    | '/contact'
    | '/gdpr'
    | '/girls'
    | '/privacy'
    | '/sales-points'
    | '/silk'
    | '/boys/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessories'
    | '/admin'
    | '/auth'
    | '/boys'
    | '/communion'
    | '/contact'
    | '/gdpr'
    | '/girls'
    | '/privacy'
    | '/sales-points'
    | '/silk'
    | '/boys/$code'
  id:
    | '__root__'
    | '/'
    | '/accessories'
    | '/admin'
    | '/auth'
    | '/boys'
    | '/communion'
    | '/contact'
    | '/gdpr'
    | '/girls'
    | '/privacy'
    | '/sales-points'
    | '/silk'
    | '/boys/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessoriesRoute: typeof AccessoriesRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BoysRoute: typeof BoysRouteWithChildren
  CommunionRoute: typeof CommunionRoute
  ContactRoute: typeof ContactRoute
  GdprRoute: typeof GdprRoute
  GirlsRoute: typeof GirlsRoute
  PrivacyRoute: typeof PrivacyRoute
  SalesPointsRoute: typeof SalesPointsRoute
  SilkRoute: typeof SilkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/silk': {
      id: '/silk'
      path: '/silk'
      fullPath: '/silk'
      preLoaderRoute: typeof SilkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-points': {
      id: '/sales-points'
      path: '/sales-points'
      fullPath: '/sales-points'
      preLoaderRoute: typeof SalesPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/girls': {
      id: '/girls'
      path: '/girls'
      fullPath: '/girls'
      preLoaderRoute: typeof GirlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communion': {
      id: '/communion'
      path: '/communion'
      fullPath: '/communion'
      preLoaderRoute: typeof CommunionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boys': {
      id: '/boys'
      path: '/boys'
      fullPath: '/boys'
      preLoaderRoute: typeof BoysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boys/$code': {
      id: '/boys/$code'
      path: '/$code'
      fullPath: '/boys/$code'
      preLoaderRoute: typeof BoysCodeRouteImport
      parentRoute: typeof BoysRoute
    }
  }
}

interface BoysRouteChildren {
  BoysCodeRoute: typeof BoysCodeRoute
}

const BoysRouteChildren: BoysRouteChildren = {
  BoysCodeRoute: BoysCodeRoute,
}

const BoysRouteWithChildren = BoysRoute._addFileChildren(BoysRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessoriesRoute: AccessoriesRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BoysRoute: BoysRouteWithChildren,
  CommunionRoute: CommunionRoute,
  ContactRoute: ContactRoute,
  GdprRoute: GdprRoute,
  GirlsRoute: GirlsRoute,
  PrivacyRoute: PrivacyRoute,
  SalesPointsRoute: SalesPointsRoute,
  SilkRoute: SilkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
